name: flow
description: A water finding app

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.1.0+2

environment: 
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_svg: ^1.1.0
  google_maps_flutter: ^2.1.8
  location: ^4.4.0
  cloud_firestore: ^3.1.18
  firebase_core: ^1.18.0
  firebase_auth: ^3.3.11
  google_sign_in: ^5.2.4
  shared_preferences: ^2.0.15
  flutter_polyline_points: ^1.0.0
  dio: ^4.0.6
  provider: ^6.0.3





dev_dependencies:
  flutter_test:
    sdk: flutter

# Adds the flutter linter
  flutter_lints: ^2.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/Flow_Icons/
    - assets/icons/svgs/
    - assets/illustrations/



  fonts:
    - family: Product Sans
      fonts:
        - asset: assets/fonts/Product Sans Bold.ttf
        - asset: assets/fonts/Product Sans Bold Italic.ttf
        - asset: assets/fonts/Product Sans Italic.ttf
        - asset: assets/fonts/Product Sans Regular.ttf


